### ISSUE TITLE
panic on long-running job

### ISSUE THREAD

**Issue by hasjohnb** [tuneinc/fasts3#15]
This was running a `fasts3 get` on around half a terabyte of files. After a few hours, I got this:

```
panic: read tcp 192.168.246.166:33521->54.231.17.209:443: read: connection reset by peer

goroutine 208 [running]:
panic(0x977000, 0xc8204f6000)
    /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/TuneOSS/fasts3/s3wrapper.(*S3Wrapper).GetAll.func1(0xc820142120, 0xc820142110, 0xc820054c60, 0xc820206f00)
    /home/johnb/src/gopath/src/github.com/TuneOSS/fasts3/s3wrapper/s3.go:228 +0x388
created by github.com/TuneOSS/fasts3/s3wrapper.(*S3Wrapper).GetAll
    /home/johnb/src/gopath/src/github.com/TuneOSS/fasts3/s3wrapper/s3.go:232 +0xf8
```

This kind of error a fairly common thing to have happen in mid-transfer, speaking generally about S3. It seems like fasts3 should handle this a little more gracefully.

**Comment by rushton** [comment]
agreed, I thought there was retry in the aws sdk for go, but if not we can add some as well as some messaging when a failure happens on `get`.

**Comment by rushton** [comment]
should also add a flag called `--skip-existing` which will skip files which already exist on the local file system, which acts as a built-in checkpoint.

**Comment by rushton** [comment]
#21 is the first part of the fix for this, will have a follow up to handle errors on file download more gracefully
